### ISSUE TITLE
[Enhancement]: x-on:data-table-row-clicked for specific table

### ISSUE THREAD

**Issue by nehegeb** [Team-Nifty-GmbH/tall-datatables#22]
### What happened?

`<div x-on:data-table-row-clicked="$wire.set('fooBar', $event.detail)">` fires for all tall-datatable within a single blade file. There doesn't seem a way to define a single table for which this should fire.

In my case I have several 'sub' tables whose entries depend on the selected row of one 'main' table at the top of the page. These 'sub' tables have to change when I click on one entry of the 'main' table, but NOT if I click on any entry of any other table.

### How to reproduce the bug

Just add `<div x-on:data-table-row-clicked="$wire.set('fooBar', $event.detail)">` within a blade file where at least two tall-datatables is present. Then check the variable $fooBar after a click on any row of any table. It always changes, no matter the table.

### Package Version

0.4.3

### PHP Version

8.1

### Laravel Version

9.52.4

### Which operating systems does with happen with?

Linux

### Notes

One possible solution would be the possibility to add the table name to the x-on like this:
`<div x-on:data-table-row-clicked="$wire.set('fooBar', $event.detail, 'LoremIpsumDataTable')">`
If a table is given, it only fires for this one. If not, then it fires for every table just like now.

**Comment by patrickweh** [comment]
in this case the event listeneres should be registered on a wrapper div outside of each datatable component:

`<div x-on:data-table-row-clicked="alert($event.detail)">
    <livewire:ticket-list />
</div>
<div x-on:data-table-row-clicked="alert($event.detail)">
    <livewire:order-list />
</div>
<div x-on:data-table-row-clicked="alert($event.detail)">
    <livewire:contact-list />
</div>`
